### PR TITLE
Generate clients

### PR DESCRIPTION
**Pull request by MarekBodingerBA**
Commit by commit.

- Create generate-client command, update axios
- Generate forms client
- Create axios instance
- Create client-forms.ts
- Axios instance Bearer
- Replace api.ts usages with generated clients and improve types
- Remove old API fns, DTOs and use generated types
- Fix logger type

There are some "@ts-expect-errors", will be fixed after https://github.com/bratislava/nest-forms-backend/issues/23 resolved. Bearer provision will be improved after Cognito refactor.

### CODE REVIEW

**Review by mpinter — CHANGES_REQUESTED** [review]
- as the clients are used from frontend, I'd take them out of the `backend` part, the idea is that if something is in backend it's server-side code only and shouldn't be used in frontend and vice-versa
- I'm a bit confused about the api client's namings, I think they might imply incorrect things - i.e. the sendAndUpdate form is a thing of forms backend - yes, it also calls on nases, but does other stuff as well that's tied to our forms backend logic. I'd rather keep the different api's names as close to our baclend services names as possible
- missing readme/docs about how the client is to be generated

Otherwise just read through, but looking good.

**Comment by MarekBodingerBA** [comment]
> I'm a bit confused about the api client's namings, I think they might imply incorrect things - i.e. the sendAndUpdate form is a thing of forms backend - yes, it also calls on nases, but does other stuff as well that's tied to our forms backend logic. I'd rather keep the different api's names as close to our baclend services names as possible

This we cannot really influence as it's generated from OpenAPI, or?

**Comment by MarekBodingerBA** [comment]
> > I'm a bit confused about the api client's namings, I think they might imply incorrect things - i.e. the sendAndUpdate form is a thing of forms backend - yes, it also calls on nases, but does other stuff as well that's tied to our forms backend logic. I'd rather keep the different api's names as close to our baclend services names as possible
> 
> This we cannot really influence as it's generated from OpenAPI, or?

https://github.com/bratislava/konto.bratislava.sk/pull/298/commits/f36de0140293f87e03ff15752ef9c6196e89a04e
Better?

**Review by mpinter — APPROVED** [review]
replies to the api naming stuff in slack. :+1: 🚢

**Pull request merged**
